config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :post_gyms, only: [:new, :create, :index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_gym
end

app/models/post_gym.rb
class PostGym < ApplicationRecord

  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_gyms, dependent: :destroy
  has_many :post_comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/post_gyms_controller.rb
class PostGymsController < ApplicationController

  def new
    @post_gym = PostGym.new
  end

  def create
    @post_gym = PostGym.new(post_gym_params)
    @post_gym.user_id = current_user.id
    @post_gym.save
    redirect_to post_gyms_path
  end

  def index
    @post_gyms = PostGym.all
  end

  def show
    @post_gym = PostGym.find(params[:id])
  end

  private
  def post_gym_params
    params.require(:post_gym).permit(:gym_name, :image, :caption)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_gyms_helper.rb
module PostGymsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iwaterro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="slidemenu">
  <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
    <% if user_signed_in? %>
      <li class="">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
      <li class="">
        <%= link_to '投稿フォーム', new_post_gym_path %>
      </li>
      <li class="">
        <!-- ↓以下のコードは、5章で正しいroutingに書き直します。 -->
        <%= link_to 'マイページ', "#" %>
      </li>
    <% else %>
      <li class="">
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li class="">
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
  </ul>
</div>

    <%= yield %>
  </body>
</html>

app/views/post_gyms/edit.html.erb
edit

app/views/post_gyms/index.html.erb
<% @post_gyms.each do |post_gym| %>
  <%= attachment_image_tag post_gym, :image %><br>
  <%= link_to post_gym_path(post_gym.id) do %>
    <%= post_gym.gym_name %><br>
  <% end %>
  <%= post_gym.caption %><br>
  <%= post_gym.user.name %><br>

<% end %>

app/views/post_gyms/new.html.erb
<%= form_with model:@post_gym, local:true do |f| %>
        <%= f.attachment_field :image %>

        <%= f.text_field :gym_name, class:"form-control", placeholder:"gym名" %>
        <%= f.text_field :caption, class:"form-control", placeholder:"gym名" %>
        <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>

<% end %>

app/views/post_gyms/show.html.erb
      <div class="post-image">
        <%= attachment_image_tag @post_gym, :image %>
      </div>
    </div>
    <div class="post-content">
      <h2 class="post-title"><%= @post_gym.gym_name %></h2>
      <ul class="meta-info-cells v4 float-wrapper">
        <li>
          <i class="fa fa-user"></i>By<a href="#">
            <%= @post_gym.user.name %></a>
        </li>
        <li>
          <i class="fa fa-calendar"></i><%= @post_gym.created_at.strftime('%Y/%m/%d') %>
        </li>
        <li>
          <i class="fa fa-heart"></i>
          <a href="#">202 いいね</a>
        </li>
        <li>
          <i class="fa fa-comment"></i>
          <a href="#comments">4</a>
        </li>
      </ul>
      <div class="post-content-inner mt-20">
        <p><%= @post_gym.caption %></p>
      </div>
    </div>